# Generated by Django 5.1.1 on 2024-09-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasedb',
            options={'verbose_name': 'Frase o Cita', 'verbose_name_plural': 'Frases o Citas'},
        ),
        migrations.AlterField(
            model_name='autordb',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fallecimiento'),
        ),
    ]
